# Light UI Fragment
# Apply this fragment to a dark theme to create a light variant.
# This overrides UI scopes while preserving syntax highlighting from the parent.

[scopes]

"ui.chrome.navbar.item.background:hover" = { bg = "@rainbow:{color-accent}-0", border = { width = 3, fg = "@rainbow:{color-accent}-100" } }

[palette]
background = "#FFF"
background-alt = "#FFF"
background-hover = "@rainbow:{color-accent}-0" # Row hover
background-overlay = "#FFF"

border-fg = "#DDDDDD"
chrome-border-fg = "#DDDDDD"
chrome-background = "#FFF"
chrome-background-hover = "@rainbow:{color-accent}-0"
chrome-background-active = "#FFF"

menu-background = "#FFF"
menu-background-hover = "@rainbow:{color-accent}-0"
menu-border =  "#DDDDDD"
