# Light UI Fragment
# Apply this fragment to a dark theme to create a light variant.
# This overrides UI scopes while preserving syntax highlighting from the parent.

[scopes]

"ui.chrome.navbar.item.background:hover" = { bg = "@rainbow:{color-accent}-1000", border = { width = 3, fg = "@rainbow:{color-accent}-900"  }  }

[palette]
background = "#000"
background-alt = "#000"
background-dim = "#000"

border-fg = "#333"
chrome-border-fg = "#333"
chrome-background = "#000"
# chrome-background-hover = "#111"
chrome-background-active = "#000"

chrome-background-hover = "@rainbow:{color-accent}-1000"
background-hover = "@rainbow:{color-accent}-1000"
