[metadata]
name = "Dark (Amethyst)"
author = "jimmyff"
brightness = "dark"
inherits = "dark-turquoise"

[scopes]
# Inherits all scopes from dark.toml

[palette]
accent-bg = "oklch(0.68 0.2007 292.24)"

syntax-title = "@rainbow:cyan-300"
syntax-strong = "@rainbow:fuchsia-300"
