[metadata]
name = "Dark (Emerald)"
author = "jimmyff"
brightness = "dark"
inherits = "dark-turquoise"

[scopes]
# Inherits all scopes from dark.toml

[palette]
accent-bg = "oklch(0.69 0.2241 157.63)"
