[metadata]
name = "Amethyst Storm"
author = "jimmyff"
brightness = "dark"
inherits = "storm-turquoise"

[variables]

color-accent = "berry"
tone-accent = "500"

[scopes]
# Inherits all scopes from dark-turquoise

[palette]

syntax-title = "@rainbow:berry-{tone-syntax-bright}"
syntax-strong = "@rainbow:cyan-{tone-syntax-bright}"
syntax-bullet = "@rainbow:fuchsia-{tone-syntax-bright}"
syntax-quote = "@rainbow:purple-{tone-syntax-medium}"
syntax-emphasis = "@rainbow:pink-{tone-syntax-bright}"
syntax-code = "@rainbow:azure-{tone-syntax-bright}"
syntax-link = "@rainbow:indigo-{tone-syntax-bright}"
