[metadata]
name = "Amethyst Storm"
author = "jimmyff"
brightness = "dark"
inherits = "storm-turquoise"

[variables]

color-accent = "berry"
tone-accent = "600"

color-task-today = "berry"
color-task-overdue = "fuchsia"
color-task-soon = "cyan"

[scopes]
# Inherits all scopes from dark-turquoise

[palette]

syntax-title = "@rainbow:berry-{tone-syntax-bright}"
syntax-strong = "@rainbow:cyan-{tone-syntax-bright}"
syntax-bullet = "@rainbow:fuchsia-{tone-syntax-bright}"
syntax-quote = "@rainbow:purple-{tone-syntax-medium}"
syntax-emphasis = "@rainbow:pink-{tone-syntax-bright}"
syntax-code = "@rainbow:azure-{tone-syntax-bright}"
syntax-link = "@rainbow:blue-{tone-syntax-bright}"
syntax-checkbox = "@rainbow:cerulean-{tone-syntax-medium}"
syntax-rule = "@rainbow:cyan-{tone-syntax-medium}"


cursor = "#ff66ff"
cursor-fg = "#000000"
