[metadata]
name = "Bastite Storm"
author = "jimmyff"
brightness = "dark"
inherits = "storm-turquoise"

[variables]

color-accent = "green"
tone-accent = "600"

[scopes]
# Inherits all scopes from storm-amethyst.toml

[palette]

syntax-title = "@rainbow:pink-{tone-syntax-medium}"
syntax-strong = "@rainbow:forest-{tone-syntax-bright}"
syntax-bullet = "@rainbow:rust-{tone-syntax-medium}"
syntax-quote = "@rainbow:turquoise-{tone-syntax-medium}"
syntax-emphasis = "@rainbow:cerulean-{tone-syntax-bright}"
syntax-code = "@rainbow:indigo-{tone-syntax-bright}"
syntax-link = "@rainbow:lemon-{tone-syntax-accent}"

syntax-checkbox = "@rainbow:crimson-{tone-syntax-medium}"
syntax-rule = "@rainbow:turquoise-{tone-syntax-medium}"
