[metadata]
name = "Sonora Sunrise Twilight"
author = "jimmyff"
brightness = "dark"
inherits = "twilight-turquoise"

[variables]

color-accent = "red"
tone-accent = "400"

color-highlight = "cyan"
color-highlight-match = "red"

color-task-today = "cyan"
color-task-overdue = "crimson"
color-task-soon = "violet"

[scopes]
# Inherits all scopes from twilight-turquoise.toml

[palette]

syntax-title = "@rainbow:cyan-{tone-syntax-bright}"
syntax-strong = "@rainbow:orange-{tone-syntax-bright}"
syntax-emphasis = "@rainbow:pink-{tone-syntax-bright}"
syntax-bullet = "@rainbow:red-{tone-syntax-medium}"
syntax-quote = "@rainbow:berry-{tone-syntax-medium}"
syntax-code = "@rainbow:indigo-{tone-syntax-bright}"
syntax-link = "@rainbow:lemon-{tone-syntax-accent}"
syntax-checkbox = "@rainbow:cerulean-{tone-syntax-medium}"
syntax-rule = "@rainbow:cyan-{tone-syntax-medium}"
